export const AGREGAR_USUARIO = 'AGREGAR_USUARIO';
export const AGREGAR_USUARIO_EXITO = 'AGREGAR_USUARIO_EXITO';
export const AGREGAR_USUARIO_ERROR = 'AGREGAR_USUARIO_ERROR';

export const INICIO_LISTAR_USUARIOS= 'INICIO_LISTAR_USUARIOS';
export const LISTAR_USUARIOS_EXITO= 'LISTAR_USUARIOS_EXITO';
export const LISTAR_USUARIOS_ERROR= 'LISTAR_USUARIOS_ERROR';

export const OBTENER_USUARIO_ELIMINAR = "OBTENER_USUARIO_ELIMINAR";
export const USUARIO_ELIMINADO_EXITO= 'USUARIO_ELIMINADO_EXITO';
export const USUARIO_ELIMINADO_ERROR= 'USUARIO_ELIMINADO_ERROR';

export const OBTENER_USUARIO_EDITAR = "OBTENER_USUARIO_EDITAR";
export const USUARIO_EDITAR_EXITO= 'USUARIO_EDITAR_EXITO';
export const COMENZAR_EDITAR_USUARIO ='COMENZAR_EDITAR_USUARIO';
export const USUARIO_EDITAR_ERROR= 'USUARIO_EDITAR_ERROR';